# Generated by Django 3.2.8 on 2021-10-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempurchased',
            name='recipes',
        ),
    ]
