# Generated by Django 3.2.8 on 2021-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_remove_itempurchased_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempurchased',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
